### ISSUE TITLE
Dovyčištění textu vybraného z HTML tagů od přebytečných čárek, teček a jiných interpunkčních znamének

### ISSUE THREAD

**Issue by mareklovci** [mareklovci/ite#2]
Je nutno dovyčistit text od veškerého přebytečného balastu, aby se mohlo začít s vytvářením _n-gramů_. Takže například `Lorem ipsum dolor. Sit amet, consectetur , adipiscing.` by mělo být upraveno na `Lorem ipsum dolor sit amet consectetur adipiscing`. Úpravu samozřejmě provést v rámci možností, nemusí to být úplně dokonalé, ale musíme být schopni dostat z toho textu nějaké rozumné _n-gramy_.

**Comment by mareklovci** [comment]
V případě, že nebudeme chtít vytvářen n-gramy, tak se to možná nemusí tak důkladně čistit. N-gramy jsou potřeba pro našeptávání.

**Comment by thonzyk** [comment]
našeptávání v ČR chceme!
